import subprocess
from sys import stdin
from PIL import Image, ImageFont, ImageDraw

width = height = 16


def gen_numb_image(i, font):
    img = Image.new("RGBA", (width, height))
    draw = ImageDraw.Draw(img)
    draw.text(((width)/2, (height)/2), text=str(i), fill="white",
              font=font, anchor="mm", align="center")
    img.save("icons/i%03d.ico" % i)


font = ImageFont.truetype("arial.ttf", 12)
for i in range(1, 100):
    gen_numb_image(i, font)

gen_numb_image(100, ImageFont.truetype("arial.ttf", 9))

# when headset not connected, zero is reported
Image.open("icons/disconnected.png").save("icons/i000.ico")

header = b"// File generated by 2goarray v0.1.0 (http://github.com/cratonica/2goarray)\n\npackage main\n\n"
skip = len(header) + len(b"var i000 []byte = []byte{\n")
with open("icon.go", "wb") as go_file:
    go_file.write(header)
    go_file.write(b"var icons [][]byte = [][]byte{\n{\n")
    for i in range(100):
        with open("icons/i%03d.ico" % i,) as icon_file:
            go_file.write(subprocess.check_output(
                ["2goarray", "i%03d" % i, "main"], stdin=icon_file)[skip:-2])
            go_file.write(b",\n{\n")
    with open("icons/i100.ico",) as icon_file:
        go_file.write(subprocess.check_output(
            ["2goarray", "i%03d" % i, "main"], stdin=icon_file)[skip:-2])
    go_file.write(b",\n}\n")
